# Publish package to npm
# - Check package.json version
# - Build project
# - Publish Build to npm

name: "Version Release"

on:
   # Triggers ONLY when you press the green "Publish release" button (not on draft‑save)
   release:
      types: [published]

# Grant minimal permissions. `id-token` enables npm provenance
permissions:
   contents: read
   id-token: write
   packages: write

jobs:
   publish:
      # Skip prereleases (remove this line if you WANT prerelease publishes)
      if: ${{ !github.event.release.prerelease }}

      runs-on: ubuntu-latest

      steps:
         - name: Checkout source
           uses: actions/checkout@v4

         # ! use: package.lock.json
         # - name: Set up Node
         #   uses: actions/setup-node@v4
         #   with:
         #      node-version: "20"
         #      registry-url: "https://registry.npmjs.org/"
         #      cache: "npm"

         - name: Setup Node.js
           uses: actions/setup-node@v2
           with:
              node-version: "20.10"

         # ! use: package.lock.json
         # - name: Install dependencies
         #   run: npm ci

         - name: Install dependencies
           run: npm install

         # —— optional: build step ——
         - name: Build
           run: npm run build --if-present

         - name: Publish to npm
           # The secret must be an "Automation" token created on npmjs.com
           env:
              NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
           run: |
              # "--access public" needed only for scoped packages
              npm publish --access public --provenance
